### PR TITLE
Add non-latin BattleTag support

### PR DESCRIPTION
**Pull request by Lord-Protector**
Cyrillic or korean for example

### CODE REVIEW

**Comment by Lord-Protector** [comment]
Yep, [Хлебушек-21845](http://masteroverwatch.com/profile/pc/eu/%D0%A5%D0%BB%D0%B5%D0%B1%D1%83%D1%88%D0%B5%D0%BA-21845). Not my account :D

**Comment by chesterhow** [comment]
Seems to be working for me. The code is now live. You can try it too! :)

**Comment by Lord-Protector** [comment]
Thanks for quick answer! I already forked your bot and launched my instance with russian localization. I thought about lang switching, but later maybe.

**Comment by Lord-Protector** [comment]
Also why you turned off webhooks? Works pretty nice on my configuration. Much faster!

**Comment by chesterhow** [comment]
Ah I saw your fork. You're doing a russian version? Neat.

Anyway I don't have an SSL cert set up and I'm currently hosting the bot for free on Heroku so thats why I left out the webhooks for now.

**Comment by Lord-Protector** [comment]
Yeah, I hope you do not mind.
I think about Xbox and PS4 support. Maybe will send pull request later.

**Comment by chesterhow** [comment]
Nope not at all :)

**Pull request merged**
